export const questionsListCapitales = [
  "Quelle est la capitale de la France ?",
  "Quelle est la capitale de l'Allemagne ?",
  "Quelle est la capitale de l'Italie ?",
  "Quelle est la capitale des Etats-Unis ?",
  "Quelle est la capitale de l'Angleterre ?",
];

export const questionsList = [
  "En HTML, quelle est la balise utilisée pour écrire le titre principal ?",
  "En HTML, quelle est la balise utilisée pour faire une liste ? <em style='font-size : 0.7rem'>(et pour les plus pointilleux, oui il y en a plusieurs...)</em>",
  "Trouver l'intrus dans cette liste",
  "Quelle balise est utilisée pour les images ?",
  "Citez un attribut HTML lié aux images",
  "Que signifie HTML ? ",
  "Que signifie CSS  ? ",
  "En CSS, quelle propriété est utilisé pour gérer la scale d'un élément ? ",
  "Quelle propriété est utilisée pour changer la couleur de fond d'un élément ?",
  "Quelle est la fonction de la propriété z-index ?",
  "Quel est le rôle de la propriété display ?",
  "À quoi sert la propriété flex-direction dans un conteneur Flexbox ?",
  "Quelle propriété est utilisée pour changer la taille du texte ?",
  "Comment centrer un élément en Flexbox à la fois horizontalement et verticalement ?",
  "Quelle propriété est utilisée pour créer des coins arrondis ?",
  "Comment applique-t-on une ombre à un élément ?",
  "Quelle propriété contrôle la transparence d'un élément ?",
  "Quelle unité de mesure est relative à la taille de la police parente ?",
  "À quoi sert la propriété position: absolute; ?",
  "Quelle propriété CSS est utilisée pour créer des espaces à l'intérieur des bordures d'un élément ?",
];

export const responsesCapitales = [
  ["Marseille", "Valenciennes", "Paris", "La Fistinière"],
  ["Munich", "Köln", "Berlin", "Le Chateau de Frankenstein"],
  ["Milan", "Rome", "Venise", "Le parc des monstres de Bomarzo"],
  ["Los Angeles", "New York", "Washington", "La Zone 51"],
  ["Londres", "Canterbury", "Manchester", "Cockermouth"],
];

export const responses = [
  ["<title></title>", "<h1></h1>", "<p></p>", '<input type="title" />'],
  ["<list></list>", "<order></order>", "<ul></ul>", '<input type="list" />'],
  ["<ol></ol>", "<h5></h5>", "<th></th>", "<img></img>"],
  ["<picture />", "<pic />", "<img />", "<link img />"],
  ["class", "src", "href", "img"],
  [
    "Hyperlink Text Management Language",
    "HyperText Markup Language",
    "Hierarchical Tagging Markup Language",
    "How To Meet Ladies",
  ],
  [
    "Central Script System",
    "Code Structure Simplifier",
    "Cascading Style Sheets",
    "Crazy Spaghetti Syntax",
  ],
  ["modulate", "resize", "transform", "set-size"],
  ["background-color", "color", "font-color", "rainbow-painter"],
  [
    "Modifier la position des éléments sur l'axe Z (avant/arrière)",
    "Contrôler la transparence d'un élément",
    "Régler la largeur des éléments",
    "Changer l'altitude d'un élément dans le cloud",
  ],
  [
    "Ajuster l'espacement entre les éléments",
    "Définir le type d'affichage d'un élément (bloc, inline, etc.)",
    "Modifier la structure d'une balise",
    "Afficher une photo du Mont Saint-Michel",
  ],
  [
    "Définir la direction des éléments à l'intérieur du conteneur",
    "Modifier l'ordre de superposition des éléments",
    "Aligner les éléments sur un axe horizontal",
    "Permettre aux éléments de pouvoir faire le grand-écart",
  ],
  ["font-size", "text-size", "size", "make-it-bigger"],
  [
    "justify-content : center; align-items: center",
    "display: block; margin: 0 auto;",
    "text-align: center;",
    "Utiliser des prières et un peu de magie",
  ],
  ["border-style", "border-radius", "box-shadow", "arrondis-toi"],
  [
    "shadow",
    "text-shadow",
    "box-shadow",
    "dire 'ombre' et espérer que ça marche",
  ],
  ["visibility", "transparency", "opacity", "see-through-mode"],
  ["em", "px", "rem", "banana"],
  [
    "Placer l'élément par rapport à son conteneur le plus proche avec position: relative;",
    "Fixer l'élément en haut de la page",
    "Garder l'élément toujours visible en défilant",
    "Permettre à l'élément d'exister dans une autre dimension",
  ],
  ["border-spacing", "margin", "padding", "inner-bubble"],
];

export const goodResponse = [
  "<h1></h1>",
  "<ul></ul>",
  "<img></img>",
  "<img />",
  "src",
  "HyperText Markup Language",
  "Cascading Style Sheets",
  "transform",
  "background-color",
  "Modifier la position des éléments sur l'axe Z (avant/arrière)",
  "Définir le type d'affichage d'un élément (bloc, inline, etc.)",
  "Définir la direction des éléments à l'intérieur du conteneur",
  "font-size",
  "justify-content : center; align-items: center",
  "border-radius",
  "box-shadow",
  "opacity",
  "rem",
  "Placer l'élément par rapport à son conteneur le plus proche avec position: relative;",
  "padding",
];
